Repository geocoder-php/Geocoder, pull requests merged in 2019-08, with the labels that each got.

#956 Here provider: additionalData field.
  src/Provider/Here/Here.php
  src/Provider/Here/Model/HereAddress.php
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_05dc4edee1d02963f60bbf5adb1cfe320adb28dc
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_1ba6e28cc3d9ae30109213b80945baf595f519bd
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_229c421e5db81a41b4f0de532b9195ca167839fc
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_294a363b1471a89d5cebdedbb9c9e1c32a5c63ee
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_36a5582aaebc9d6af6dc1a7f777ccc81567d734c
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_5231ce19ffb0c5b984c6dcb36d9aaca333306f9b
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_52a8643238b53d4d6eba428ed41adb94d4cfdfce
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_568e9a86ad0ea25a7d96879480b8d739a407ddf4
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_5c87aa54346ca08a46c825ae26575f3363b459ef
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_5d75a64d228221ba42d4e3a66700e72ccebbb07b
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_602a32128f305283be3b6767f80a9446e11679c2
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_65e76d7e375f40596d1d113a8ee7bba427546cab
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_6e9817062e449d1e8abe16e3cabbce4772837fa0
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_716027455f33cb7d524f67d327885b09634b8d9d
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_7946d0ea5639b8bc4cd49b3b85a1295a76c59049
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_7eed14785b6e0e6a48d8395380b6f699bf691e90
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_8e56b01c7b879c4b01ceb44d997d48f2370a49d8
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_91d6fd4f43fb33d34698e75a5f003da0609c5822
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_c125989e1cef79078a1e1ef71edfc8f231919b01
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_c999273b877baf75ca587c9e22b826866a864bce
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_cebd9db8aab43ed6294129d8fece29a53e76e337
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_d579014fc8dff5e3c4f4cb3da9c56cdc3c8733d2
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_df7debbdd05fb3f4515cfa84e014b085b9d43897
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_e97187a9ce40104919c0b7d0fec967ab7d002fab
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_edd4ef22e219dcd4d7df7bf44d076bda305e1bb9
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_ee23926ce9ba0369a48c81f408fcc0c482e71a4d
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_f4823c2cc2840722f688f1d64b45169a513bef76
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_f651f003020b73ca93e5ef22164029e2f6f90cc2
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_fb4df3dc6e02f9fcf3a5b1ad5dc826441e5329d0
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_fb952a0852054250bc056af0ec3bd1b6f278e79f
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_fef6bd8f86eb0bf4dd62aeadd178176cb741e333
  src/Provider/Here/Tests/.cached_responses/geocoder.api.here.com_ffffba9e9db77837f37f34fb367f57db33a8c133
  src/Provider/Here/Tests/.cached_responses/geocoder.cit.api.here.com_4a71a23e8ce6f7dbe5ede16c8c294ead1405cc84
  src/Provider/Here/Tests/.cached_responses/geocoder.cit.api.here.com_e709f1be28b2e052d53f6fea26c74c42ff97057f
  src/Provider/Here/Tests/HereTest.php
Labels: improvement, provider

#993 [Here] Update CHANGELOG.md
  src/Provider/Here/CHANGELOG.md
Labels: documentation

#997 Fix Nominatim provider when "missing" osm_id and osm_type
  src/Provider/Nominatim/Nominatim.php
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_388d03935611eb4bd1d69d1d91b5af2fd70ec24f
  src/Provider/Nominatim/Tests/NominatimTest.php
Labels: bug, provider

#998 [Nominatim] Update CHANGELOG.md
  src/Provider/Nominatim/CHANGELOG.md
Labels: documentation

#1001 Update README.md
  README.md
Labels: documentation

#1004 New Pelias provider
  src/Provider/Pelias/CHANGELOG.md
  src/Provider/Pelias/LICENSE
  src/Provider/Pelias/Pelias.php
  src/Provider/Pelias/README.md
  src/Provider/Pelias/Tests/IntegrationTest.php
  src/Provider/Pelias/Tests/PeliasTest.php
  src/Provider/Pelias/composer.json
  src/Provider/Pelias/phpunit.xml.dist
Labels: provider

#1009 chore: update docs email/badge
  README.md
Labels: documentation
