Repository geocoder-php/Geocoder, pull requests merged in 2021-06, with the labels that each got.

#1127 [Nominatim] add support for optional address fields and extra tags
  src/Provider/Nominatim/Model/NominatimAddress.php
  src/Provider/Nominatim/Nominatim.php
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_08a4a6fa86e15d460984b411fffa3351225b3c7c
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_0b7c89ad04ee5a2d884a2fb4b718a1d54ff09d87
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_334be5ea0b6f1f56a64fb35bb1691181b9b09a55
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_388d03935611eb4bd1d69d1d91b5af2fd70ec24f
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_4939a920dd5843ce1fc74ce0203702d79748f489
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_587636b4f0e7139858b4390498946009583bc32d
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_592b89bc385fdb5a1035c78dbbe53f2140ba2489
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_5ff6cd6f94ae2f70cf5300217327b77f9eda7435
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_614a4d899e5e7e47380278075f00be15637686c6
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_7bc67c1f5d09c8956972d7bac599ad32378be808
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_87528fbc3e65ded1ae76c5f7e6ee56afa13a768c
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_8934d1c4f224d07cc55e360ed2935e46fbd817db
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_a84be68761b075cd458d22b786f69413e45524dc
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_a9667f4b7f1f26f7b60b36e7f495f8f022aee2bc
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_c28a54e57adfc2a7eef9b7030329b565c6a1b829
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_df0465e67865e45cc50318e1db838c320b5fb977
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_dfdc355642ef34fb9970df028c4ec338ce0ea3f4
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_e52647a4ee81d8138eb99f6c112982f37b855f91
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_e658d32d515e8afcd12e81f3456b06507f0523ac
  src/Provider/Nominatim/Tests/.cached_responses/nominatim.openstreetmap.org_e8352e6fc34f5bcef068abe10c06931df6826767
  src/Provider/Nominatim/Tests/IntegrationTest.php
  src/Provider/Nominatim/Tests/NominatimTest.php
Labels: provider

#1125 Replace empty() by more strict checks
  src/Common/Dumper/AbstractArrayDumper.php
  src/Common/Model/Address.php
  src/Common/Model/AddressBuilder.php
  src/Common/Model/AddressCollection.php
  src/Common/Model/AdminLevelCollection.php
  src/Common/ProviderAggregator.php
  src/Common/Query/GeocodeQuery.php
  src/Common/StatefulGeocoder.php
  src/Http/Provider/AbstractHttpProvider.php
  src/Plugin/Plugin/LimitPlugin.php
  src/Plugin/Plugin/LocalePlugin.php
  src/Provider/Pelias/Pelias.php
  src/Provider/TomTom/TomTom.php
Labels: improvement

#1128 Fix LocalePlugin
  src/Plugin/Plugin/LocalePlugin.php
Labels: bug
